# datasets settings
data_source: opus_books
lang_src: en
lang_dst: it
tockenizer_file: configs/tockenizer_{0}.json

# model settings
model_folder: weights
model_basename: tmodel_
preload: latest
logs_folder: runs/tmodel

# training settings
batch_size: 32
num_epochs: 10
learning_rate: 5e-5
d_model: 512
seq_len: 128

